name: API CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman

    - name: Install kong deck
      uses: kong/setup-deck@v1

    - name: Check kong deck connection
      run: deck gateway ping --kong-addr https://e472-103-97-164-230.ngrok-free.app

    - name: Start deck sync
      run: deck gateway sync --kong-addr https://e472-103-97-164-230.ngrok-free.app kong.yml

    - name: Run API tests
      run: newman run postman/fact-service-test.postman_collection.json

    - name: Shut down Docker
      run: docker compose -f kong/docker-compose.yml down
